### ISSUE TITLE
geocodes.json을 시트에 올리기

### ISSUE THREAD

**Issue by raccoonyy** [NullFull/jonmat-archive#4]

**Comment by majecty** [comment]
했습니다.
[식당 시트](https://docs.google.com/spreadsheets/d/1vjCUzjeNxnNZ-ZaaNLM4fx2n_ephZDjpJSSvJGUVm0U/edit#gid=937234432)에 geocodes.json의 위경도 정보를 추가했습니다.

지금의 [02_get_geocdes.py](https://github.com/NullFull/jonmat/blob/e20105eab4bc3cf0ee0de9a80d731c85058f112c/02_get_geocodes.py)가 생성하는 geocdes.json은 위치와 위경도 정보만 가지고 있습니다. 02_get_geocodes.py 파일을 살짝 수정해서 식당 이름도 같이 출력하게 변경하여 작업했습니다. 생성된 json파일을 CSV파일로 변환하여 구글 스프레드시트에서 import했습니다.

**Comment by lexifdev** [comment]
진행한 내용이어서 이슈를 정리합니다.
