### ISSUE TITLE
2017 네이버 시트에 있는 위경도 데이터랑 (geocodes.json을?) 합치기

### ISSUE THREAD

**Issue by raccoonyy** [NullFull/jonmat-archive#5]

**Comment by majecty** [comment]
식당 naver + google 시트 만들었어요.
https://docs.google.com/spreadsheets/d/1vjCUzjeNxnNZ-ZaaNLM4fx2n_ephZDjpJSSvJGUVm0U/edit#gid=2015788390

**Comment by majecty** [comment]
구글 관련 데이터는 _식당_ 시트에서 가져왔습니다.
네이버 관련 정보는 _jonmat2017_naver_ 시트에서 가져왔습니다.

**Comment by raccoonyy** [comment]
👍

**Comment by lexifdev** [comment]
진행된 내용이라 이슈를 정리합니다.
