### ISSUE TITLE
CSV publish 데이터를 이용하기

### ISSUE THREAD

**Issue by raccoonyy** [NullFull/jonmat-archive#8]

**Comment by majecty** [comment]
이 [문서](https://docs.google.com/spreadsheets/d/1vjCUzjeNxnNZ-ZaaNLM4fx2n_ephZDjpJSSvJGUVm0U/edit#gid=1764752662) 중 jonmat2017 시트가 이미 웹에 퍼블리시 되어있네요.

다음 커맨드로 다운받을 수 있습니다.
```
curl -L https://docs.google.com/spreadsheets/d/1vjCUzjeNxnNZ-ZaaNLM4fx2n_ephZDjpJSSvJGUVm0U/export\?format\=csv\&gid\=1764752662 --output jonmat-2017.csv
```

**Comment by lexifdev** [comment]
진행 하셨던 내용이라 이슈를 닫습니다.
