### ISSUE TITLE
vercel의 파이썬 빌드 사용 가능할지 확인하기

### ISSUE THREAD

**Issue by raccoonyy** [NullFull/jonmat-archive#9]
https://vercel.com/docs/runtimes#official-runtimes/python

**Comment by majecty** [comment]
다른 언어를 빌드과정에서 사용할 경우 직접 해당 언어 빌드 환경을 설정하라고 되어있네요.

아래 이미지처럼 rust를 쓰고 싶다면 `amazon-linux-extras install rust1` 를 쓰라고 합니다.
![image](https://user-images.githubusercontent.com/709900/137125184-26a18dfa-3b49-43f9-964c-35215cef1439.png)

아마존 리눅스 도커 이미지에서 직접 확인해봤는데, python은 다음 명령어로 설치할 수 있습니다. `amazon-linux-extras install python3.8`

위 내용은 [여기](https://vercel.com/docs/concepts/deployments/build-step)에서 찾아봤습니다.

**Comment by lexifdev** [comment]
새로운 저장소로 이전하며 이슈를 정리합니다.
새로운 버전에서는 Vercel이 기본으로 잘 지원하는 js로 빌드 하게 바뀌었습니다.

https://github.com/NullFull/jonmat-next
